name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration release --no-restore

    - name: Test
      run: dotnet test --configuration release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration release --no-build --output .

 # Publish to NuGet and GitHub Packages
    - name: Publish
      if: github.event_name == 'push'
      run: |
        dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
        dotnet nuget push *.nupkg --source 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json' --api-key '${{ github.token }}' --skip-duplicate
